name: Development
on: [push]

jobs:
  build:
    name: Lint and Kover
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Lint
        run: |
          ./gradlew lintKotlin --stacktrace

      - name: Tests
        run: |
          ./gradlew koverVerify --stacktrace
